baseURL = "https://nathanhuisman.xyz/"
title = "Nathan Huisman"
theme = "PaperMod"
defaultContentLanguage = "en"
enableRobotsTXT = true
buildDrafts     = false
buildFuture     = false
buildExpired    = false

[minify]
    disableXML   = true
    minifyOutput = true

[languages]
    [languages.en]
        weight = 10
        [languages.en.params]
            [languages.en.params.profileMode]
                enabled = true
                title = "NathanHuisman.xyz"
                subtitle = "Bottom Text\n\nI don't know what to do with this website yet"
                imageUrl = "/images/computerman_square.webp"
                imageTitle = "Computer Man!!!1!"
                imageWidth  = 240
                imageHeight = 240
    [languages.nl]
        weight = 10
        [languages.nl.params]
            [languages.nl.params.profileMode]
                enabled = true
                title = "NathanHuisman.xyz"
                subtitle = "Bottom Text\n\nIk weet nog niet wat ik met deze website ga doen"
                imageUrl = "/images/computerman_square.webp"
                imageTitle = "Computer Man!!!1!"
                imageWidth  = 240
                imageHeight = 240
[params]
    env = "production"
    custom_css = ["custom.css"]
    
    keywords = ["Blog", "Portfolio", "Nathan Huisman"]
    DateFormat = "September 20, 2003"
    defaultTheme = "auto"
    ShowReadingTime  = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs  = true
    ShowCodeCopyButtons   = false
    disableSpecial1stPost = false
    disableScrollToTop    = false
    comments    = false
    hidemeta    = false
    hideSummary = false
    showtoc     = false
    tocopen     = false

    [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/nathan_huismus"
    [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/huisman_nathan"
    [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/nathan-huisman-212b6b200/"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10
